graphprotocol/indexer-rs

- service/src/graph_node.rs
- service/src/query_processor.rs
- service/src/server/routes/network.rs
- service/src/server/routes/subgraphs.rs
Mostly to make it behave like the original `indexer-service`.
> fix: subgraph queries responses

- service/src/query_processor.rs
- service/src/server/routes/subgraphs.rs
It seems that the subgraph queries take `:id` as ipfs hash of a subgraph as well as the hex representation. 
og indexer-service [constructs](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-service/src/server/index.ts#L249C28-L249C28) subgraph deployment id which calls out to common-ts [here](https://github.com/graphprotocol/common-ts/blob/f300c979bc1c2f643826439f06c0cec5c95a2a4b/packages/common-ts/src/subgraphs/index.ts#L27C4-L27C4)
> fix: take QmHash to construct subgraph deployment id

- README.md
- service/src/server/mod.rs
quick fix to include `Bearer ` prefix as in previous indexer-service ([line](https://github.com/graphprotocol/indexer/blob/a73b7dd41791e2ea44a45f79641939e687434abf/packages/indexer-service/src/server/index.ts#L208))
Network subgraph auth token does not have such an operation in comparison
> fix: add 'Bearer ' prefix to supplied free query auth token

- service/src/graph_node.rs
- service/src/query_processor.rs
To make it easier to send out network queries for things like allocation tracking, etc.
Also made the API slightly more explicit.
> feat: network_query w/ gql and vars

- service/src/graph_node.rs
- service/src/main.rs
- service/src/query_processor.rs
Small change that will make it easier to share the graph-node instance wrapper with other flows, such as the allocation monitor.
> refactor: move graph-node instance to main

- Cargo.lock
- service/Cargo.toml
- service/src/main.rs
- service/src/server/routes/mod.rs
Add slower ratelimiter (9000/30min == 5/s) to subgraph health checks and operator information
Add network ratelimiter (90000/30min == 50/s) to public status API and network subgraph queries
part of https://github.com/graphops/indexer-service-rs/issues/5
> feat: slow and network ratelimiter

- Cargo.lock
- service/Cargo.toml
- service/src/allocation_monitor.rs
- service/src/common/allocation.rs
- service/src/common/mod.rs
- service/src/common/types.rs
- service/src/config.rs
- service/src/main.rs
It doesn't have the Attestation bits yet.
Should behave like the one in `indexer-service`.
Fixes #25
> feat: AllocationMonitor

- service/src/allocation_monitor.rs
- service/src/common/mod.rs
- service/src/common/network_subgraph.rs
- service/src/graph_node.rs
- service/src/main.rs
- service/src/query_processor.rs
- service/src/server/mod.rs
- service/src/server/routes/network.rs
Isolate network subgraph from query processor, so that network queries are separated from subgraph queries.
Network subgraph serves free queries with auth token, whereas paid queries should come through `subgraphs/id/:id` with the deployment ID and receipts
> refactor: splits network subgraphs query to NetworkSubgraph

- Cargo.lock
- service/Cargo.toml
- service/src/allocation_monitor.rs
- service/src/common/allocation.rs
- service/src/common/types.rs
- service/src/main.rs
- service/src/query_processor.rs
- service/src/util.rs
There is some weirdness due to type conversions to interface with the `native` crate. I think it'd be nice to refactor `native` to have it rely on external dependencies, to make it easier to understand and maintain in the future.
> feat: attestation signers added to allocation monitor

- service/src/metrics/mod.rs
- service/src/server/routes/subgraphs.rs
Track query volume and performance like the original indexer service.
Some metrics from the original are registered but not used so they are not included here
Part of https://github.com/graphops/indexer-service-rs/issues/4
For later: Add cost model metrics once there is cost server
> Feat: record query metrics

- Cargo.lock
- service/Cargo.toml
- service/src/allocation_monitor.rs
- service/src/attestation_signers.rs
- service/src/main.rs
- service/src/query_processor.rs
- service/src/test_vectors.rs
Now can subscribe to `AllocationMonitor` updates, so `AttestationSigners` knows when to update its signers list. Makes way for TAP to also watch the `AllocationMonitor`.
Note: Moved some test vectors out of allocation_monitor.rs to share them amongst test files.
Fixes #41
> refactor: splitting off  `AttestationSigners`

- .github/workflows/tests.yml
- service/src/common/indexer_management_client/resolver.rs
> ci: enabling SQLX/PG tests

- service/src/server/routes/status.rs
The title says it all. Noticed that these are failing the pipeline on `main`.
> fix: resolve clippy errors introduced recently

- Cargo.lock
- common/Cargo.toml
- common/src/allocations/monitor.rs
- common/src/network_subgraph/mod.rs
- common/src/types.rs
- service/src/escrow_monitor.rs
- service/src/server/routes/network.rs
- service/src/server/routes/status.rs
Based on #59, will need to be rebased after that is merged.
I am working on breaking down #54 into smaller PRs. This is the first of these.
> Improve querying the network subgraph, deserializing result data etc.

- service/src/metrics/mod.rs
Fixes https://github.com/graphops/indexer-service-rs/issues/61
(need to rebase after https://github.com/graphops/indexer-service-rs/pull/59 gets merged)
> fix: remove name label from QUERY_DURATION metrics

- service/src/common/indexer_management/mod.rs
This implements @aasseman's suggestion from https://github.com/graphops/indexer-service-rs/pull/63#discussion_r1355483452.
> Reduce cost model test code

- common/src/allocations/monitor.rs
- common/src/network_subgraph/mod.rs
- common/src/test_vectors.rs
- service/src/main.rs
This is based on #65 and will need to be rebased after that has been merged. Only the most recent commit in this PR is actually new.
> Type network subgraph deployment strongly

- common/src/allocations/mod.rs
- common/src/allocations/monitor.rs
- common/src/attestations/signer.rs
- common/src/test_vectors.rs
- service/src/query_processor.rs
- service/src/tap_manager.rs
We may need to add these back later for other purposes, but indexer-service does not need these fields; the only reason it queries allocations is to create attestation signers for them.
There might be even more fields that we could remove. However, signalled_tokens in particular is necessary at the moment because there is buggy data in the real-world network subgraph where the field is negative sometimes. That breaks U256 parsing. Since we don't need this and the other fields, I thought it best to remove them.
> fix: remove irrelevant fields from deployment queries

- common/src/attestations/dispute_manager.rs
- common/src/attestations/mod.rs
- common/src/attestations/signers.rs
- common/src/lib.rs
- service/src/main.rs
This is clearly better than having to define it on the command line. 😁 
Also, the dispute manager _miiiiight_ change over time, so an eventual is nice to make sure we stay on top of that.
> feat: add dispute manager eventual

- common/src/allocations/monitor.rs
- common/src/attestations/dispute_manager.rs
- common/src/lib.rs
- common/src/subgraph_client.rs
- service/src/main.rs
- service/src/server/mod.rs
This way we can also it for the escrow subgraph and others that we may need in the future.
This is based on #71 and will need to be rebased when that has been merged.
> Generalize NetworkSubgraph into SubgraphClient

- service/src/main.rs
Because the indexer-service arguments are asking for ms:
https://github.com/graphops/indexer-service-rs/blob/b603c306969e1a202ea15381438cde3a5204dcc3/service/src/config.rs#L211-L218
https://github.com/graphops/indexer-service-rs/blob/b603c306969e1a202ea15381438cde3a5204dcc3/service/src/config.rs#L260-L267
(I'll fix clap for this second one later)
This is carried from the original `indexer-service`. Even though asking for seconds directly may make more sense, that would introduce a breaking change for users.
> fix(service): ms intervals treated as seconds

- service/src/config.rs
- service/src/main.rs
This adds the config options, `chain_id` & `verifying_contract`, required to contruct the EIP-712 domain used when verifying receipts.
> fix: add config for receipts domain

- common/src/tap_manager.rs
Previsously, paid queries would stall until timeout while awaiting the initial eventual value for escrow accounts. This change avoids the delay, such that the intended error message is returned.
> fix: fail fast when escrow accounts are missing

- common/src/allocations/monitor.rs
- common/src/attestations/dispute_manager.rs
- common/src/escrow_accounts.rs
- common/src/subgraph_client/client.rs
- service/src/main.rs
Ideally, a single `reqwest::Client` is reused so that they use the same connection pool. This also provides a clearer point to set timeout policies, etc. and removes an unused error case.
> fix: share HTTP client between `DeploymentClient`s

- Cargo.lock
- common/Cargo.toml
- common/src/allocations/monitor.rs
- common/src/attestations/dispute_manager.rs
- common/src/attestations/signers.rs
- common/src/escrow_accounts.rs
- common/src/indexer_errors.rs
- common/src/subgraph_client/client.rs
- common/src/subgraph_client/monitor.rs
- common/src/tap_manager.rs
Previously, all logs emitted from the common package would not appear.
> fix(common): replace log with tracing

- common/src/subgraph_client/monitor.rs
Fix filter key for `monitor_deployment_status` 
For https://github.com/graphprotocol/indexer-rs/issues/89
> fix: indexing statuses filter key

- common/src/subgraph_client/client.rs
- service/src/main.rs
Indexer service takes in 
```
graph_node_query_endpoint // commonly 'http://localhost:8000'
graph_node_status_endpoint // commonly 'http://localhost:8030/graphql'
```
`DeploymentDetails::for_graph_node` currently generalized `graph_node_base_url` for both 
- `status_url` by appending `/status`
- `query_url` by appending `/subgraphs/id/:id`
I made updates to use the configured `--graph-node-status-endpoint` for `status_url` instead of `graph_node_query_endpoint`. 
Resolves https://github.com/graphprotocol/indexer-rs/issues/89
> fix: graph-node-status-endpoint for DeploymentDetail status_url

- .dockerignore
- .github/workflows/containers.yml
- .github/workflows/tests.yml
- Dockerfile.indexer-service-rs
- Dockerfile.indexer-tap-agent
For indexer-service-rs and indexer-tap-agent.
Standardized tests and containers around Debian Bookworm. Liberally building and pushing containers for new version tags, pushes to main, and pull requests (to facilitate testing).
I did some testing on my fork here: https://github.com/aasseman/indexer-service-rs/pkgs/container/indexer-service-rs
> ci: build and push container images

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/indexer_service/http/config.rs
- common/src/indexer_service/http/indexer_service.rs
- common/src/indexer_service/http/metrics.rs
- common/src/indexer_service/http/mod.rs
- common/src/indexer_service/http/request_handler.rs
- common/src/indexer_service/http/scalar_receipt_header.rs
- common/src/indexer_service/mod.rs
- common/src/lib.rs
- common/src/tap_manager.rs
- common/src/test_vectors.rs
- service/Cargo.toml
- service/build.rs
- service/src/main.rs
- service/src/server/mod.rs
- service/src/util.rs
This introduces a framework for writing any type of HTTP-based indexer service using a skeleton like the one below. A working implementation for one of the upcoming data services already exists, my next goal is to port the existing subgraph indexer-service in this repository to this framework as well. But that will happen in a separate PR.
```rust
#[async_trait]
impl IndexerServiceImpl for MyService {
type Error = MyServiceError;
type Request = MyServiceRequest;
type Response = MyServiceResponse;
type State = MyServiceState;
async fn process_request(
&self,
manifest_id: DeploymentId,
request: Self::Request,
) -> Result<(Self::Request, Self::Response), Self::Error> {
Ok((request, MyServiceResponse::new("some response", true)))
}
}
#[tokio::main]
async fn main() -> Result<(), Error> {
// …
```
> Create indexer service framework

- docs/example-service-config.toml
> chore(docs): Add docs/ directory and example service config file

- tap-agent/src/agent.rs
- tap-agent/src/main.rs
The current implementation implements the `Drop` trait for the manager by aborting the handler. 
The manager was being dropped at the end of `create_agent()` and wouldn't execute the thread correctly. This PR transfer the ownership to the main function which is dropped correctly when the execution is terminated.
> fix: drop the manager handler correctly

- .sqlx/query-a24f3bde2965abe825d896dd7fd65783fea041032e08b6c7ecd65a4b6599a81c.json
- .sqlx/query-cbf8955f0b6bd355b56b448497abcf6325e1ee9a10e5be9d8cbc919fbb8c87f7.json
- migrations/20230912220523_tap_receipts.down.sql
- migrations/20230912220523_tap_receipts.up.sql
- migrations/20230915230734_tap_ravs.down.sql
- migrations/20230915230734_tap_ravs.up.sql
- tap-agent/src/tap/sender_allocation_relationship.rs
Fixes #98 
Note that for now there is no easy way to unit test this because of how `tap_core` is designed.
> feat: store failed receipts and RAVs

- .sqlx/query-7ff23083cf2afaf2c6b9693736053136baee1406f48f61db2b7bc504825a6fc3.json
- tap-agent/src/tap/sender_allocation_relationship.rs
It's smaller than it looks, most of the diff is about splitting `rav_quester_try()` into multiple functions to help with readability.
> Refactor rav requester

- common/src/subgraph_client/monitor.rs
The subgraph client monitor was sending malformed queries to graph-node.
subgraph monitor logs:
```
WARN indexer_common::subgraph_client::monitor: Error querying deployment status for `QmP9foCa7YRvQJCtrdPV1zu1yVovwagEpcDSarvmQKS642`: Failed to query status of deployment `QmP9foCa7YRvQJCtrdPV1zu1yVovwagEpcDSarvmQKS642`: Error deserializing GraphQL response body: expected value at line 1 column 1
```
Graph-node logs:
```
ERRO IndexNodeService call failed: GraphQL server error (query error): query parse error: Parse error at 1:2\nUnexpected `"query"[StringValue]`\nExpected `Name`\n, component: IndexNodeServer
```
Changing the query body to use `indexer_common::subgraph_client::client:Query` fixes the problem.
I also fixed a small inconsequential typo: graph-node's status GQL API actually …
> fix(common): subgraph monitor query

- common/src/tap_manager.rs
- tap-agent/src/tap/mod.rs
- tap-agent/src/tap/rav_storage_adapter.rs
- tap-agent/src/tap/receipt_storage_adapter.rs
- tap-agent/src/tap/sender_allocation_relationship.rs
- tap-agent/src/tap/test_utils.rs
Standardize around lowercase hex string  (without leading '0x')
> fix: TAP addresses formatting in DB

- tap-agent/src/agent.rs
Quick fix before we update to a more recent version of `tap-core` that provides a single source of truth for the EIP-712 domain separator.
> fix(tap-agent): EIP712 domain separator name

- Cargo.lock
- common/Cargo.toml
- common/src/allocations/mod.rs
- common/src/allocations/monitor.rs
- common/src/attestations/dispute_manager.rs
- common/src/attestations/signer.rs
- common/src/attestations/signers.rs
- common/src/escrow_accounts.rs
- common/src/indexer_service/http/config.rs
- common/src/indexer_service/http/indexer_service.rs
- common/src/indexer_service/http/scalar_receipt_header.rs
- common/src/signature_verification.rs
- common/src/tap_manager.rs
- common/src/test_vectors.rs
- service/Cargo.toml
- service/src/database.rs
- tap-agent/Cargo.toml
- tap-agent/src/aggregator_endpoints.rs
- tap-agent/src/config.rs
- tap-agent/src/tap/escrow_adapter.rs
- tap-agent/src/tap/mod.rs
- tap-agent/src/tap/rav_storage_adapter.rs
- tap-agent/src/tap/receipt_checks_adapter.rs
- tap-agent/src/tap/receipt_storage_adapter.rs
- tap-agent/src/tap/sender_allocation_relationship.rs
- tap-agent/src/tap/sender_allocation_relationships_manager.rs
- tap-agent/src/tap/test_utils.rs
Fixed the versions of `toolshed` crates to proper tags.
Also, replaced direct usage of `alloy_primitives::Address` to the toolshed re-export `thegraph::types::Address` to enforce `alloy` version compatibility between `indexer-rs` and other projects that depend on `toolshed`.
Note that the `tap_core` dependency is based on a custom branch based off of `tap_core` v0.7.0 on which the same treatment was applied. This is temporary as for now `tap_core`'s main branch contains a lot of breaking changes.
> build(deps): fix toolshed deps

- Cargo.lock
- service/Cargo.toml
This is needed because the gateway knows we're running TAP if the indexer-service version is >= 1.0.0
> chore: set indexer-service version to 1.0.0-alpha.0

- common/src/indexer_service/http/indexer_service.rs
update from `Json(address)` to more like the existing format of `Json(operator: address)`
Addressing https://github.com/graphprotocol/indexer-rs/pull/120#issuecomment-1937089863
> operator info endpoint to return an object

- common/src/indexer_service/http/scalar_receipt_header.rs
I was having trouble receiving scalar receipts, so took a look at how the gateway construct the receipt, found that it creates receipt's header with capital letters `HeaderName::from_str("Scalar-Receipt").unwrap(),` from [line](https://github.com/edgeandnode/graph-gateway/blob/f32e5f33447d27f6425fa2754f64bc1b5acfe1ef/graph-gateway/src/indexer_client.rs#L66)
indexer framework process header with just lower-case `scalar-receipt`. I *think* the convention uses capital letters so proposing a change here. if not, I can propose a change on the gateway's side.
> fix: capitalize scalar receipt header

- common/src/indexer_service/http/scalar_receipt_header.rs
Reverts graphprotocol/indexer-rs#126
As per `HeaderName::from_static` documentation https://docs.rs/http/latest/http/header/struct.HeaderName.html#method.from_static. This panics if it's not lowercase and gets into a poisoned state because of lazy_static! use
> Revert "fix: capitalize scalar receipt header"

- Cargo.lock
- common/Cargo.toml
The newer version for toolshed correctly displays the original message that failed to be deserialized
> fix: use better error handling for subgraph query

- tap-agent/src/agent/sender_allocation.rs
- tap-agent/src/config.rs
Added to config a limit  that will define the amount of receipts to aggregate per request
fixes #96
> Add limit of receipts per rav request

- tap-agent/src/config.rs
- tap-agent/src/main.rs
A metrics config port was unnecessarily added in #156 , and created a conflict in clap that breaks argument parsing completely.
> fix(tap-agent): metrics port config

- .sqlx/query-6389d2951877d3211943268c36145f3665501acea0adadea3f09695d0503ee7b.json
- .sqlx/query-6d1c71ee8f32e696e6a091b37ec415ca3e12356f3418a376980e5458fee7e200.json
- .sqlx/query-7487b58e603ccc4ac2e55e676295517040b78eb9bba04c9db33229fe52f85259.json
- .sqlx/query-a15f95e1e74e806a6bbc355139b6af57911eb79e5233e80bb08f6e5ef6d14fc9.json
- tap-agent/src/agent/sender_account.rs
- tap-agent/src/config.rs
Fixes #103. (the remaining half)
Adds a new setting `max_unnaggregated_fees_per_sender` (in GRT).
When a sender's unaggregated fees go over that value, it gets added to the `scalar_tap_denylist`, which tells the indexer-service to refuse service from that sender.
When the unaggregated fees come back under the value, it gets removed from the `scalar_tap_denylist`, which tells the indexer-service to accept service from that sender again.
> feat(tap-agent): Deny senders over max_unnaggregated_fees_per_sender

- service/src/database.rs
Another small thing I caught while familiarizing myself with the code, this removes the need to create an intermediate vector when merging models in `database`.
> refactor(database): streamline model merging

- tap-agent/src/agent/sender_accounts_manager.rs
- tap-agent/src/agent/sender_allocation.rs
Noticed some typos as well as potentially confusing docs on the monitoring items.
Also, RAV and unaggregated fees gauges were not updated at the right places.
Sorry for not having caught these in review in the first place :face_with_diagonal_mouth:
> fix(tap-agent): monitoring labels and gauge updates

- tap-agent/src/agent/sender_account.rs
> feat: auto retry RAVs if sender denied

- Cargo.lock
- common/Cargo.toml
- common/src/allocations/monitor.rs
Updating `thegraph-core` to https://github.com/edgeandnode/toolshed/releases/tag/thegraph-core-v0.5.2 to get this fix: https://github.com/edgeandnode/toolshed/pull/233
> Fix empty response err on GQL return empty list

- .github/renovate.json5
This PR adds the [Renovate[bot]](https://www.mend.io/renovate/) configuration file to automate the dependency tracking and update.
The remaining step is to enable the Renovate GitHub App for this repo.
> chore(ci): add renovate bot

- common/src/subgraph_client/client.rs
After recent refactoring, `[subgraphs.*.query_url]` is broken in config resulting in double slash in query url in the client
What happens is `query_url` deserializes into Url, then gets converted to String with a trailing slash (even if originally it didn't have it), then appended with `/subgraphs/id/Qmxxx`, resulting in double-slash that graph-node can't handle
i.e. `http://query-node:8000` -> `http://query-node:8000/` -> `http://query-node:8000//subgraphs/id/Qmxxx`
This PR fixes it
> Fix `query_url` in config

- .github/renovate.json5
Update renovate config to group all `build-info` crate updates
> chore(ci): group all build-info upgrade PRs

- common/src/subgraph_client/client.rs
This integration test depends on the now "defunct" hosted service, so the test always fails.
I am disabling it until we find a solution to this dependency on the hosted service.
> chore(common): disable integration test depending on the hosted service

- tap-agent/src/agent/sender_allocation.rs
The Unaggregated fees metric was not updating on last RAV.
> fix(tap-agent): unaggregated_fees metric last RAV

- common/src/indexer_service/http/config.rs
- common/src/indexer_service/http/indexer_service.rs
- service/src/config.rs
> fix(common,service): make receipt_max_value u128

- service/src/service.rs
Similar issue as https://github.com/graphprotocol/indexer-rs/pull/228 but for subgraph queries. This PR fixes the double-slash issue.
> fix double-slash in subgraph query url

- tap-agent/src/main.rs
We are currently printing the contents of the config in the logs at the debug level. While that was useful at early testing stage,  we should now drop it before it gets used on mainnet.
> fix(tap-agent): never log config

- Cargo.lock
- config/Cargo.toml
- config/maximal-config-example.toml
- config/src/config.rs
Having the possibility of supplying all of the configuration using environment variables is already a requested feature.
This makes sure that we can do so, even for nested configuration fields.
With this, nesting it handled with double underscore in env var name, example:
```
INDEXER_SERVICE_SUBGRAPHS__NETWORK__QUERY_URL = http[...]
```
> feat(config): env support for nested fields

- common/src/allocations/monitor.rs
Because the hosted service has been shut down.
We don't have a clear solution for an API key yet.
> test(common): ignore tests needing hosted service

- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_allocation.rs
The older logic retried by sending the same value again, but other parts of the code could update the unaggregated fees value and this would set to an older state.
This PR removes the update unaggregated fees from the retry logic.
> fix(tap-agent): update retry logic

- config/default_values.toml
- config/minimal-config-example.toml
Add max_willing_to_lose into the default config values
fixes #312
> fix: Remove max_willing_to_lose

- docs/dashboard.json
- tap-agent/src/agent/sender_account.rs
Change hardcoded trigger value of 1000 to a metric tap_rav_request_trigger_value
fixes #313
> fix: Rename trigger rav to Rav trigger

- tap-agent/src/agent/sender_allocation.rs
> fix: Add more information if rav request is timing out

- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_accounts_manager.rs
- tap-agent/src/agent/sender_allocation.rs
- tap-agent/src/agent/sender_fee_tracker.rs
> feat: add tracker for buffer unaggregated fees

- config/src/config.rs
> fix: add warn where trigger_value is below 0.1 grt

- config/maximal-config-example.toml
> fix: config comment of using both queryurl and deployment_id

- common/src/indexer_service/http/config.rs
- config/maximal-config-example.toml
- config/minimal-config-example.toml
- config/src/config.rs
- service/src/config.rs
- tap-agent/src/config.rs
> fix: Add option to give either postgres_url or values individually

- tap-agent/src/agent/sender_account.rs
This also creates a new function which does the check for inital denial of a sender
fixes #338
> feat: Add a warning in case senders are undenied manually from db

- config/src/config.rs
- service/src/cli.rs
- service/src/service.rs
- tap-agent/src/config.rs
> fix: Accept config to be through file or env vars

- config/src/config.rs
> feat: Make it possible to have a shared env var for srvice and tap

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/allocations/monitor.rs
- common/src/attestations/dispute_manager.rs
- common/src/escrow_accounts.rs
- common/src/subgraph_client/client.rs
- graphql/allocations.query.graphql
- graphql/dispute.query.graphql
- graphql/epoch.query.graphql
- graphql/escrow_account.query.graphql
- graphql/network.schema.graphql
- graphql/tap.schema.graphql
- graphql/test.schema.graphql
- graphql/transactions.query.graphql
- graphql/unfinalized_tx.query.graphql
- graphql/user.query.graphql
- tap-agent/Cargo.toml
- tap-agent/src/agent/sender_account.rs
- tap-agent/src/tap/context/checks/allocation_id.rs
> refactor: use graphql_client crate

- service/src/main.rs
- tap-agent/src/config.rs
> Debug config info

- Cargo.toml
If you try to compile directly `service` after compiling other components, you need to do `cargo clean && cargo build`. By adding this flag, you don't have to clean and rebuild
> chore: add ansi feature flag for subscriber

- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_allocation.rs
- tap-agent/src/agent/sender_fee_tracker.rs
> feat: Move backoff to to the tracker to remove errors

- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_accounts_manager.rs
- tap-agent/src/agent/sender_allocation.rs
- tap-agent/src/agent/sender_fee_tracker.rs
> perf: trigger rav request concurrently

- common/src/allocations/monitor.rs
- common/src/attestations/signers.rs
- common/src/tap.rs
- common/src/tap/checks/allocation_eligible.rs
- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_accounts_manager.rs
Fixes #364 
Hi, please have a look when you're free, and as usual tell me if any changes has to be made
> refactor: use tokio::watch for allocations

- graphql/escrow_account.query.graphql
Thought I'd add some docs while I was working with these GraphQL queries...
---
[TAP-261](https://linear.app/semiotic/issue/TAP-261/document-escrow-account-query)
> docs(graphql): add docs for escrow account query

- .github/renovate.json5
- graphql/allocations.query.graphql
- graphql/escrow_account.query.graphql
This PR Closes #308 
Changes in this PR
- Updated the curl requests and responses in `Readme.md` file
- Added a missing supported field `blockHashFromNumber` for indexingStatus
- Added a route `/subgraph/health/<deployment-id>` to check the health of subgraphs from local graph-node
> Update example endpoints in Readme.md and add missing endpoint

- tap-agent/src/agent/sender_allocation.rs
With the new buffer, refreshing the unaggregated fees does not get to the latest state.
For it to happen, we need to refresh the whole database.
This is not supposed to happen because we only mark it as last after it was closed for 1 hour, but in case something goes wrong, we shouldn't miss anything.
> fix: refresh database before closing allocation

- common/src/tap.rs
- common/src/tap/checks/value_check.rs
The last PR was merged, but we still don't have it enabled in indexer-agent. Disabling for now
> fix: disable value check

- common/src/indexer_service/http/indexer_service.rs
We had a refactor(#409) that updated the duplication of code in configurations. But while doing that, status_url was misconfigured. With the latest refactor (#428), we crash early if we cannot start some services.
Indexer service on version 1.2.0 is not capable of starting up if you provide local deployment (graph-node + deployment_id)
> fix: proper build graph-node query url

- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_allocation.rs
- tap-agent/src/tap/context/checks/allocation_id.rs
> refactor: use tokio::watch for allocation id check

- common/src/allocations/monitor.rs
- common/src/attestations/dispute_manager.rs
- common/src/escrow_accounts.rs
- common/src/indexer_service/http/indexer_service.rs
- common/src/subgraph_client/client.rs
- common/src/subgraph_client/monitor.rs
- tap-agent/src/agent.rs
- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_accounts_manager.rs
- tap-agent/src/agent/sender_allocation.rs
- tap-agent/src/tap/context/checks/allocation_id.rs
> refactor: use tokio::watch for subgraph monitor

- README.md
- common/src/indexer_service/http/health.rs
- common/src/indexer_service/http/indexer_service.rs
- common/src/indexer_service/http/mod.rs
- common/src/subgraph_client/client.rs
- graphql/indexing_status.schema.graphql
- graphql/subgraph_health.query.graphql
This PR is the second part of #408
> feat: add subgraph health endpoint 

- config/src/config.rs
> fix: ignore empty environment variables strings

- common/src/watcher.rs
- tap-agent/src/agent/sender_account.rs
- tap-agent/src/agent/sender_accounts_manager.rs
Fixes #456 
- Please have a look when you're, hope I covered all, if any changes required tell me.
> pipe function for watcher.rs and replaced usage

- .github/workflows/containers.yml
With the last update in crates, the container build was broken. Fixing it.
> ci: fix container build

- crates/common/src/subgraph_client/monitor.rs
- crates/graphql/subgraph_deployment_status.graphql
> refactor: use graphql-client for status monitor

- Cargo.lock
- crates/monitor/src/deployment_to_allocation.rs
- crates/monitor/src/lib.rs
- crates/service/Cargo.toml
- crates/service/src/error.rs
- crates/service/src/lib.rs
- crates/service/src/metrics.rs
- crates/service/src/middleware.rs
- crates/service/src/middleware/inject_allocation.rs
- crates/service/src/middleware/inject_deployment.rs
- crates/service/src/middleware/inject_labels.rs
- crates/service/src/middleware/inject_receipt.rs
- crates/service/src/middleware/inject_sender.rs
- crates/service/src/middleware/metrics.rs
- crates/service/src/middleware/prometheus_metrics.rs
- crates/service/src/routes/request_handler.rs
- crates/service/src/service.rs
- crates/service/src/service/indexer_service.rs
- crates/watcher/src/lib.rs
> refactor: create metrics middleware

- .sqlx/query-6c05fc541bf0bb2af20fbe62747456055d5ebda5cb136d9d015f101ebbfe495f.json
- Cargo.lock
- Cargo.toml
- crates/service/Cargo.toml
- crates/service/src/error.rs
- crates/service/src/middleware.rs
- crates/service/src/middleware/auth.rs
- crates/service/src/middleware/auth/bearer.rs
- crates/service/src/middleware/auth/or.rs
- crates/service/src/middleware/auth/tap.rs
- crates/service/src/middleware/inject_context.rs
- crates/service/src/middleware/inject_receipt.rs
- crates/service/src/routes/request_handler.rs
- crates/service/src/service.rs
- crates/service/src/service/indexer_service.rs
- crates/service/src/service/tap_receipt_header.rs
Signed-off-by: Gustavo Inacio <gustavo@semiotic.ai>Signed-off-by: Gustavo Inacio <gustavo@semiotic.ai>
> refactor: add auth middleware

- crates/service/src/middleware.rs
- crates/service/src/middleware/tap_context.rs
- crates/service/src/service/indexer_service.rs
- crates/service/src/tap.rs
- crates/service/src/tap/checks/deny_list_check.rs
- crates/service/src/tap/checks/sender_balance_check.rs
We shouldn't waste computation on things that we already have.
> refactor: use sender in tap context

- crates/service/src/error.rs
- crates/service/src/metrics.rs
- crates/service/src/middleware/attestation.rs
- crates/service/src/middleware/labels.rs
- crates/service/src/middleware/prometheus_metrics.rs
- crates/service/src/routes/static_subgraph.rs
- crates/service/src/service/router.rs
- crates/service/tests/router_test.rs
- crates/service/tests/snapshots/router_test__full_integration_test-2.snap
> fix: update status code for errors

- crates/tap-agent/src/agent/sender_accounts_manager.rs
> fix: start listening to messages after start up

- Cargo.lock
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent/sender_accounts_manager.rs
> fix: shutdown tap-agent if db connection lost

- crates/service/src/routes/request_handler.rs
> feat: add graph-indexed header in subgraph query response

- crates/config/default_values.toml
- crates/config/maximal-config-example.toml
- crates/config/src/config.rs
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
This PR fixes this issue https://github.com/graphprotocol/indexer-rs/issues/532
I've tested the image by building it and pushing to docker hub.
This screenshot is without the config (failing):
This screenshot is with the config (success):
```
[tap]
sender_timeout_secs = 120
```
> fix: add receipts timeout config

- Cargo.lock
- Cargo.toml
This pull request includes updates to dependencies in the `Cargo.toml` file. The most significant changes involve updating versions and modifying feature sets for specific dependencies.
Dependency updates:
* Updated `thegraph-graphql-http` to version `0.3.2` and added the `reqwest` feature.
* Removed the `subgraph-client` feature from `thegraph-core`.
> chore(deps): enable the right thegraph-graphql-http feature

- crates/service/src/routes/health.rs
- docs/Queries.md
This fixes a response payload previously using an `error` field, which is invalid for GraphQL over HTTP.
> fix: invalid serialization of CheckHealthError

- crates/service/src/middleware/attestation.rs
The indexer-service has not been properly forwarding the `graph-indexed` header because the attestation middleware discarded all headers set by the handler.
> fix: retain headers in attestation middleware

- .sqlx/query-4c857a980b1eddc4fa85ccad223762d85614c249e06180e0b8dda8e14eff93f4.json
- .sqlx/query-661b961e286d8591d1eaaf29d3bdf5748c361f3d4c4136b8d5b3a3c3af5fcc9e.json
- .sqlx/query-6fc518e6b980f6dcc160d8310fc7e761625a862578b61ce925910c351edbbda8.json
- Cargo.lock
- crates/dips/src/lib.rs
- crates/dips/src/server.rs
- crates/service/src/database/dips.rs
- crates/service/src/routes/request_handler.rs
- crates/service/src/service.rs
- crates/service/src/tap/checks/sender_balance_check.rs
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/tap-agent/src/lib.rs
- crates/tap-agent/src/tap/context/receipt.rs
- crates/tap-agent/src/test.rs
- crates/tap-agent/tests/sender_account_manager_test.rs
- crates/tap-agent/tests/sender_account_test.rs
- crates/tap-agent/tests/tap_agent_test.rs
This new tests cover are here to enhance the testing experience and help ensure tap V2 wont affect the processes in a "bigger picture"
As well as added more test types around receiving receipts. For this a new method was added regarding batch inserts for receipts into the DB, trying to be have a more accurate representation of how TAP works on a day to day basis.
Regarding the tests on the "bigger picture" , tests for several layers were added.
Such as a full process from sender account all the way from starting it, creating a sender allocation up to the point of marking allocation as last for redeeming.
Another test added from the sender account manager layer which tries to do the same process as the previous layer but starting from the manager.
And finally a test for the full Tap Agent …
> test: integration tests for tap-agent

- Cargo.lock
- Cargo.toml
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/tap-agent/src/tap/context.rs
- crates/tap-agent/src/tap/context/escrow.rs
- crates/tap-agent/src/tap/context/rav.rs
- crates/tap-agent/src/tap/context/receipt.rs
- crates/tap-agent/src/test.rs
- crates/tap-agent/tests/sender_account_manager_test.rs
- crates/tap-agent/tests/sender_account_test.rs
- Create `NetworkVersion` trait used to define what kind of allocation we are handling.
- Add Generic for TapContext over NetworkVersion.
- Add Legacy and Horizon that implement `NetworkVersion`
- Wrap allocation Id address with new `AllocationId` enum.
- Create TapManager version depending on the allocation id variant.
- Implement aggregation within NetworkVersion trait.
- Add aggregator_v2 connection for SenderAccount.
TODO for future PRs:
- Implement all unimplemented traits for database queries.
- Test more extensively different types of allocations running.
tap-agent is not well organized and we have a few files with 1k+ lines. Suggestions on how to organize are accepted.
> refactor: aggregate ravs depending on allocation type

- .sqlx/query-10bd83671f30f7bc2096e9158be60023577bbbdbab7a83788204d066bdd9fec5.json
- .sqlx/query-5f0c42c9a92a446d37b2971175df6ed0cd31da6b57918a2d600ef90adce1345d.json
- .sqlx/query-6ce2133a20924d5098fa2e27f897e871955e9eb8a0a6f8b9f23a3f38597793f6.json
- .sqlx/query-8b904cecdd8e9c5dd0cd8a0dbc2e8a19c2197f08d576e5cbf978e39432bb3d5a.json
- .sqlx/query-b94514ce9abc8be15ba3b5a67f33ead0d83e409210ce5e711932bcb32888f2bf.json
- .sqlx/query-cd279b9b74e3efdb79ece086b1e6713d2fc766e6553568df8c6ab1d39a5282f6.json
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/tap-agent/src/tap/context.rs
- crates/tap-agent/src/tap/context/rav.rs
- crates/tap-agent/src/tap/context/receipt.rs
- crates/tap-agent/src/test.rs
- Simply filling the gaps that was missing with unimplemented!()
- Using rstest to provide different fixtures with different contexts to the same test
> refactor: implement receipt traits for horizon

- crates/config/maximal-config-example.toml
- crates/config/src/config.rs
- crates/dips/src/lib.rs
- crates/dips/src/server.rs
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/test.rs
- crates/tap-agent/tests/tap_agent_test.rs
Add feature for configuration that allows some senders to spend up to `max_amount_willing_to_lose` over the balance.
> feat: add escape hatch to trusted senders

- .sqlx/query-9a11e8e814e42113c91050acf54c2e847f24a2e086abcbe8e7be618f84d58f78.json
- .sqlx/query-b467894d499541f2bca15965f38ee551ece8619860f3fbcb184ebded33898cbd.json
- .sqlx/query-f65b5a6c2149155d69fb1f187ebb4e24c08d5763d97da4e2ec759c30d6170a68.json
- .sqlx/query-fa31900971e23fdf98dd48fcd649e04328fb1e758a0b538319c5fb132251a7ed.json
- Cargo.lock
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent/sender_allocation.rs
- migrations/20250131122241_tap_horizon_receipts.down.sql
- migrations/20250131122241_tap_horizon_receipts.up.sql
Create a trait called `DatabaseInteractions`.
All calls to databases are delegated to trait like:
- mark_rav_last
- calculate_fee_until_last_id
- delete_receipts_between
store_invalid_receipts is implemented in two functions and we use `partition_map` to provide the correct Vector for each
> refactor: use correct db tables in sender allocation

- .sqlx/query-1b12436e72e588d745645c4c5286b3503319e12ac9bdf25ef67942d86aa68508.json
- .sqlx/query-27a9c5a16714c8551c8921e4012bceda54664d0f41228f60b3a0f7f601cf9923.json
- .sqlx/query-712d6c51098b981a3a84908eda1b4530d70a5c1a9d6ecaeed59f20a63914d723.json
- .sqlx/query-75125066518ed99d12c1cf4e738ca058c0d7886ca33932434c72ca82a8073567.json
- crates/tap-agent/src/agent/sender_account.rs
- migrations/20250212211337_tap_horizon_sender_denylist.down.sql
- migrations/20250212211337_tap_horizon_sender_denylist.up.sql
- Add denylist table.
- Filling the blanks where `unimplemented!()`
> refactor: implement sender account for horizon

- crates/tap-agent/src/agent/sender_accounts_manager.rs
- migrations/20250131122241_tap_horizon_receipts.up.sql
- Enable listening to horizon receipts, they should have the same structure since receipts are minimal and we don't need to carry all fields.
> refactor: listen to v2 receipts

- .sqlx/query-f1d8dcf24c9677ef789469d37733f354c5d246db5bb1506839cd7b07cdcc7065.json
- Cargo.lock
- Cargo.toml
- crates/monitor/src/escrow_accounts.rs
- crates/monitor/src/lib.rs
- crates/service/Cargo.toml
- crates/service/src/middleware/sender.rs
- crates/service/src/service/router.rs
- crates/service/src/tap.rs
- crates/service/src/tap/checks/deny_list_check.rs
- crates/service/src/tap/checks/sender_balance_check.rs
- crates/service/tests/router_test.rs
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent.rs
- crates/test-assets/Cargo.toml
- crates/test-assets/src/lib.rs
- migrations/20250212211337_tap_horizon_sender_denylist.down.sql
- migrations/20250212211337_tap_horizon_sender_denylist.up.sql
- Add denylist pgnotify for horizon tables
- Update service test to listen to horizon tables
- Remove typed_builder in favor of bon
- Rename `indexer_monitor::escrow_accounts` to `indexer_monitor::escrow_accounts_v1`
- Update service router to receive v1 and v2 escrow account watchers
- Add router creation of escrow account v2 if not provided
- Update SenderBalanceCheck to route between v1 and v2 accordingly
- Update sender middleware to use the correct escrow_account monitor
> refactor: update check escrow receipt check

- Cargo.lock
- crates/dips/Cargo.toml
- crates/dips/build.rs
- crates/dips/src/database.rs
- crates/dips/src/ipfs.rs
- crates/dips/src/lib.rs
This pull request includes various changes to the `crates/dips` package to introduce feature flags and improve modularity. The key changes involve adding feature flags for optional dependencies, modifying the build script to conditionally compile based on features, and updating imports and module definitions accordingly.
* Added feature flags `rpc` and `db` in `Cargo.toml` to conditionally include dependencies (`[crates/dips/Cargo.tomlR6-R35](diffhunk://#diff-271b41f6df2e65a887a3a18cd20536fb075df359339939c77d15843c117a070cR6-R35)`).
* Updated dependencies in `Cargo.toml` to be optional based on the feature flags (`[crates/dips/Cargo.tomlR6-R35](diffhunk://#diff-271b41f6df2e65a887a3a18cd20536fb075df359339939c77d15843c117a070cR6-R35)`).
* Modified `build.rs` to conditionally compile proto …
> chore(dips): add rpc and db feature flags to indexer-dips crate

- crates/dips/package-lock.json
- crates/dips/package.json
- crates/dips/tsconfig.json
Originally I didn't include this to keep the js footprint in this repo minimal, but it's causing issues in the indexer repo...
> fix(dips): publish js files in the dips-proto npm package

- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/tap-agent/src/tap/context.rs
- crates/tap-agent/src/tap/context/rav.rs
- crates/tap-agent/src/tap/context/receipt.rs
- crates/tap-agent/src/test.rs
Introduce more usages of `bon` to improve the readability and usage of some big functions, and simplify a few test cases by defaulting to a common value.
To help find functions that have a big arity (ie many arguments) I built a helper CLI that uses tree-sitter to query the project: https://github.com/TypeLevelConsoli/rust-arity-scan
> refactor: use builder pattern to improve readability of big functions

- crates/service/src/tap/checks/value_check.rs
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/tap-agent/src/lib.rs
- crates/tap-agent/src/test.rs
- crates/tap-agent/tests/sender_account_manager_test.rs
- crates/tap-agent/tests/sender_account_test.rs
- crates/tap-agent/tests/tap_agent_test.rs
- crates/test-assets/src/lib.rs
TestableActors uses an `Arc<Notify>` to know when their messages are triggered, but that only notifies a mute signal, no context or message is gathered. By changing it to `mpsc::channel` instead, we can receive the message passed and compare it to that we sent.
> refactor: use channels on TestableActor to be able to verify sent messages

- Cargo.lock
- crates/monitor/Cargo.toml
- crates/monitor/src/client/monitor.rs
- crates/service/Cargo.toml
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/test-assets/Cargo.toml
- crates/test-assets/src/lib.rs
Added `rstest`:
- with this several tests have been refactored to only receive fixtures created on `rstest`
this PR aims to make the tests more easy reading and only focusing on the important bits per test
Due to the nature of async fixtures some tests could use them since the test itself needed to be in some order for it to work as intended.
> test: add rstest and fixtures

- crates/service/src/error.rs
Updates the SubgraphServiceError implementation to return proper JSON-formatted responses, consistent with IndexerServiceError. This fixes JSON parsing errors in GraphQL clients when handling error cases, for example introspection queries
> Fix SubgraphServiceError to return JSON-formatted error responses

- Cargo.lock
- crates/service/Cargo.toml
- crates/service/src/tap/receipt_store.rs
Skip the processing of receipts of a version, when there's no receipt for that version.
This should fix our release issue, as we won't try to access horizon tables when processing v1 receipts anymore.
> fix: skip processing of receipts when there's no receipt for a version

- .github/workflows/tests.yml
- Cargo.lock
- Cargo.toml
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/agent/sender_allocation.rs
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_account__tests__update_allocation_ids-2.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_account__tests__update_allocation_ids-3.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_account__tests__update_allocation_ids.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_accounts_manager__tests__create_allocation_id.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__close_allocation_no_pending_fees.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__execute-2.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__execute.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__failed_rav_request-2.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__failed_rav_request.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__rav_request_when_all_receipts_invalid-2.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__rav_request_when_all_receipts_invalid-3.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__rav_request_when_all_receipts_invalid.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__receive_new_receipt.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__should_return_invalid_receipts_on_startup-2.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__should_return_invalid_receipts_on_startup.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__should_update_unaggregated_fees_on_start.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__trigger_rav_request-2.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__trigger_rav_request-3.snap
- crates/tap-agent/src/agent/snapshots/indexer_tap_agent__agent__sender_allocation__tests__trigger_rav_request.snap
- crates/tap-agent/src/tap/context/receipt.rs
- justfile
Add `insta` for snapshot testing messages instead of constructing the expected result.
Insta will automatically compare the message with the snapshot during `just test` (or `cargo test`, `cargo nextest run`), and fail if the message diverges.
To review changes, it's recommended to use `cargo-insta` CLI, but it's not necessarily needed.
Please, read the create `Getting started` docs for a introduction to the recommended workflow: https://insta.rs/docs/quickstart/
> refactor(tap-agent): use insta for snapshot testing messages

- crates/service/src/error.rs
- crates/service/src/middleware/attestation.rs
- crates/service/src/middleware/attestation_signer.rs
This PR improves error reporting and logging in our middleware components(for attestation) without changing their existing behavior. It addresses issues where errors in middleware functions were neither reported in response bodies(just an error code) nor logged via tracing, making debugging unnecessarily difficult.
Key Changes
- Added structured error responses using `ErrorResponse` for better client feedback
- Implemented detailed tracing logs for error conditions, however, the current interface does not treat them as errors but as optional state changes. 
- Maintained backward compatibility with the existing middleware chain behavior
- Added explicit error/warning messages when signers are missing but attestation is requested
Fixes #619 - Error results from middleware functions not …
> Enhance middleware error reporting and logging without breaking changes

- crates/dips/src/lib.rs
- crates/dips/src/server.rs
This pull request includes several changes to the `crates/dips` module, focusing on adding a protocol version constant, fixing a typo, improving error handling, and refactoring code for better maintainability. Below are the most significant changes:
* Added a new constant `PROTOCOL_VERSION` to define the protocol version as `1` in `crates/dips/src/lib.rs`.
* Enhanced the `From<DipsError>` implementation for `tonic::Status` to provide more detailed error messages by formatting the error value in `crates/dips/src/lib.rs`.
> feat(dips): implement error reporting

- Cargo.lock
- crates/dips/Cargo.toml
- crates/dips/src/lib.rs
This pull request includes changes to the `Cargo.toml` and `lib.rs` files in the `crates/dips` directory.
* [`crates/dips/src/lib.rs`](diffhunk://#diff-43049e4db6e400dbf78fe60574626cb162e14dbb774b13f92bc9b05b68d08830L204-R209): Refactored the signature handling in the `SignedIndexingAgreementVoucher` implementation to use `Signature::try_from` to fix the signature deserialization bug.
> fix(dips): deserialize dips message signature from bytes

- Cargo.lock
- crates/dips/Cargo.toml
- crates/dips/src/ipfs.rs
This pull request includes several changes to the `crates/dips` project to update dependencies and refactor the IPFS client implementation. The most important changes include modifying the dependency versions in `Cargo.toml`, updating the import statements in `ipfs.rs`, and refactoring the `IpfsClient` struct.
* [`crates/dips/Cargo.toml`](diffhunk://#diff-271b41f6df2e65a887a3a18cd20536fb075df359339939c77d15843c117a070cL29): Removed the `ipfs-api-prelude` dependency.
* [`crates/dips/src/ipfs.rs`](diffhunk://#diff-ca88c155ef694ceb70a734514fba168b1bd873c4efc481be50c7b8dab0b59aaaL4-L12): Removed unused imports (`http::Uri`, `ipfs_api_prelude::{IpfsApi, TryFromUri}`, and `tracing`). Updated the imports to use `ipfs_api_backend_hyper::{IpfsApi, TryFromUri}`.
* …
> fix(ipfs): use from_str IPFS client constructor

- crates/dips/src/lib.rs
- crates/monitor/src/escrow_accounts.rs
This pull request includes changes to improve logging and error handling in the `validate_and_create_agreement` function and adds detailed tracing in the `get_escrow_accounts_v1` function. The most significant changes include adding the agreement ID to debug logs, enhancing error logs, and adding a trace log for escrow accounts response.
* [`crates/dips/src/lib.rs`](diffhunk://#diff-43049e4db6e400dbf78fe60574626cb162e14dbb774b13f92bc9b05b68d08830L340-R345): Added agreement ID to debug logs for better traceability when validating and creating agreements. [[1]](diffhunk://#diff-43049e4db6e400dbf78fe60574626cb162e14dbb774b13f92bc9b05b68d08830L340-R345) [[2]](diffhunk://#diff-43049e4db6e400dbf78fe60574626cb162e14dbb774b13f92bc9b05b68d08830R362-R419)
* …
> feat(dips): enhance logging with agreement ID in DIPs processing

- crates/service/src/tap/receipt_store.rs
- crates/tap-agent/src/agent.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
This PR temporarily disables Horizon support within the TAP agent to prevent potential issues due to its incomplete implementation. It also includes several improvements to enhance overall agent stability, error handling, and logging clarity.
Key Changes:
1.  **Forcibly Disable Horizon:** Overrides the `horizon_enabled` configuration setting to `false` in `agent.rs` upon startup, ensuring Horizon features remain inactive regardless of the user's config file settings.
2.  **Operator Warning for Override:** Adds a `tracing::warn!` message to notify operators if Horizon was enabled in their configuration, explaining that it has been forcibly disabled temporarily.
3.  **Conditional Horizon Components:** Prevents the creation and initialization of Horizon-specific components (like …
> Fix: Temporarily disable Horizon, enhance agent stability and logging

- Cargo.lock
- Cargo.toml
- crates/allocation/Cargo.toml
- crates/attestation/Cargo.toml
- crates/config/Cargo.toml
- crates/dips/Cargo.toml
- crates/monitor/Cargo.toml
- crates/service/Cargo.toml
- crates/tap-agent/Cargo.toml
- crates/tap-agent/src/test.rs
- crates/test-assets/Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/receipt.rs
- alphabetize the workspace dependencies
- use the workspace where feasible
- where `dips` dependencies have been touched the `dips` version has been used in the workspace version
> organize dependencies

- crates/tap-agent/src/agent/sender_allocation.rs
I've heard from indexers who hit this error and I think it may be helpful to include extra info in the warning log to help them examine their database.
> feat: improve sender allocation logging

- crates/service/src/tap/checks/deny_list_check.rs
This was always placeholder code to map out how the v2 path would look. This fixes an obvious bug in the unused v2 code.
> fix(tap): fix unused v2 deny list check

- setup-test-network.sh
The gateway service was failing to initialize properly because the escrow contract wasn't being funded correctly. This was causing the gateway's health check to fail with connection reset errors, even though the container was running.
- Added proper error handling and logging for the escrow funding process
- Integrated the escrow funding into the main setup script at the correct point (after gateway deployment, before health check)
This also has the benefit of using local-network configuration directly in our funding instead of defining constants.
Previous funding script remains in place, maybe useful out of the local-testnet setup
> Fix gateway initialization by properly funding escrow during setup

- contrib/PROFILING.md
This just updates profiling documentation to include instructions on how to run our load test
> improve profiling docs

- crates/config/default_values.toml
- crates/config/maximal-config-example.toml
- crates/config/minimal-config-example.toml
Adds E&N and GraphOps Gateway tapp aggregator endpoints to default values of the tap config
> feat: add tap sender aggregator endpoints to default config

- setup-test-network.sh
This PR updates our local testing infrastructure to use a [`semiotic-ai/local-network` fork](https://github.com/semiotic-ai/local-network/tree/suchapalaver/main-no-dipper) of `edgeandnode/local-network`.
Until now, we’ve been pinning to a specific commit to maintain compatibility. Moving to a fork based on main gives us a cleaner foundation and puts us in a better position to track upstream changes—especially the `horizon` branch—while also fixing broken components and improving support for private submodules. With every team maintaining their own branches anyway, this gets us unblocked and contributing to a more functional baseline.
SIgned off by Joseph Livesey <joseph@semiotic.ai>
--
Tested locally on PopOS:
```terminal
All services are now running!
You can enjoy your new local network …
```
> test(setup-test-network): use semiotic-ai local-network fork

- .github/workflows/containers.yml
This PR updates the CI release workflow to use a RELEASE_TOKEN secret instead of the default GITHUB_TOKEN. The default token cannot trigger workflows that are defined as reusable or that call other actions due to GitHub’s security restrictions. The RELEASE_TOKEN is a personal access token with appropriate scopes, enabling the release workflow to trigger dependent workflows such as Docker image publishing or changelog generation.
> ci(containers): use RELEASE_TOKEN for releases

- crates/attestation/src/lib.rs
- crates/config/src/config.rs
- crates/dips/src/database.rs
- crates/dips/src/ipfs.rs
- crates/dips/src/lib.rs
- crates/dips/src/server.rs
- crates/monitor/src/client/subgraph_client.rs
- crates/monitor/src/escrow_accounts.rs
- crates/profiler/src/lib.rs
- crates/service/src/metrics.rs
- crates/service/src/middleware/auth.rs
- crates/service/src/middleware/auth/bearer.rs
- crates/service/src/middleware/deployment.rs
- crates/service/src/service.rs
- crates/service/src/tap/receipt_store.rs
- crates/tap-agent/src/agent/sender_account.rs
- crates/tap-agent/src/agent/sender_accounts_manager.rs
- crates/tap-agent/src/metrics.rs
- crates/tap-agent/src/tap/context/escrow.rs
- crates/tap-agent/src/tap/context/rav.rs
- crates/tap-agent/src/tap/context/receipt.rs
- crates/tap-agent/src/test.rs
- integration-tests/src/load_test.rs
- integration-tests/src/metrics.rs
- integration-tests/src/rav_tests.rs
If you update your Rust version with `rustup update` you'll start getting a lot of warnings, which this takes care of 👍 
> refactor(clippy): fix updated warnings for rust 1.88

- Cargo.lock
> build: update cargo dependencies

- crates/tap-agent/src/agent.rs
Problem: The tap-agent was crashing because it tried to create the escrow_accounts_v2 channel before checking if Horizon (V2) was active. Since V2 is not active, the network subgraph doesn't have the paymentsEscrowAccounts field, causing the GraphQL query to fail.
Thanks @rotarur fr reporting!
> fix(tap-agent): check horizon is active before checking for escrow

- .github/workflows/containers.yml
This PR fixes CI workflow issues that were preventing `release-please` from running correctly
---
- Ensures only **one** `release-please` job runs at a time
- **Newer runs cancel older ones** to prevent race conditions
- Hopefully 🤞fixes `"Error updating ref"` permission errors
- `release-please` now only runs on **pushes to `main`**
- Prevents it from running on pull requests
- Matches expected behavior: **releases are created from `main` only**
- Added conditional logic to `builds-linux` job
- Ensures builds run even if `release-please` is skipped
---
> ci: add release-please concurrency settings

- Cargo.lock
- Cargo.toml
Fixes a breaking change from `ractor` 0.15.6 to 0.15.7 that requires `tokio_runtime` to be enabled.
---
> fix(build): enable ractor tokio-runtime

- contrib/indexer-service/start.sh
- crates/service/src/middleware/auth/tap.rs
- crates/service/src/middleware/tap_receipt.rs
- crates/service/src/service/tap_receipt_header.rs
- crates/watcher/src/lib.rs
- integration-tests/src/constants.rs
- integration-tests/src/main.rs
- integration-tests/src/rav_tests.rs
- integration-tests/src/signature_test.rs
- integration-tests/src/utils.rs
- setup-test-network.sh
This integrates the gateway into the local testing infra using local-network.
The indexer service was listening internally in the tests on a different port. We now handle channel closures instead of panicking. We're still debugging issues around receipts and signing when running the local network, so we've added debug logging for those processes. And then this works on our testing infra to integrate testing the gateway in the local testing setup.
**NOTE**: you still need to restart the indexer-service and tap-agent after `just setup` completes
---
> test: use gateway in local network testing

- crates/service/src/tap/receipt_store.rs
The indexer-service was incorrectly storing V2 (Horizon) receipt CollectionId values in the
database by truncating them from 32 bytes to 20 bytes. This caused TAP agent database notification
parsing to fail.
In `crates/service/src/tap/receipt_store.rs:348-350, the DbReceiptV2::from_receipt()` function was
calling `.as_address()` on the CollectionId before encoding:
```
let collection_id = thegraph_core::CollectionId::from(receipt.message.collection_id)
.as_address()  // ❌ This truncates 32-byte CollectionId to 20-byte address
.encode_hex();
```
Remove `.as_address()` call to store the full 32-byte CollectionId
Is this correct?
> Store full CollectionId in V2 receipt database records
