graphprotocol/indexer-rs

README.md, service/src/main.rs, service/src/server/routes/deployment.rs, service/src/server/routes/mod.rs, service/src/server/routes/subgraphs.rs
=> feat: deployment health server

.github/workflows/license_headers_check.yml, native/src/attestation.rs, native/src/lib.rs, native/src/signature_verification.rs, service/src/common/address.rs, service/src/common/database.rs, service/src/common/indexer_error.rs, service/src/common/mod.rs, service/src/common/query_fee_models.rs, service/src/common/schema.rs, service/src/common/verifier.rs, service/src/config.rs, service/src/graph_node.rs, service/src/main.rs, service/src/metrics/mod.rs, service/src/model/mod.rs, service/src/query_fee/allocations.rs, service/src/query_fee/mod.rs, service/src/query_processor.rs, service/src/server/mod.rs, service/src/server/routes/basic.rs, service/src/server/routes/deployment.rs, service/src/server/routes/mod.rs, service/src/server/routes/network.rs, service/src/server/routes/status.rs, service/src/server/routes/subgraphs.rs, service/src/util.rs
Resolves https://github.com/graphops/indexer-service-rs/issues/11
=> Add apache-2 license headers

Cargo.lock, native/src/attestation.rs, service/Cargo.toml, service/src/graph_node.rs, service/src/query_processor.rs, service/src/server/routes/subgraphs.rs
This is just a partial implementation with a lot of TODOs to get the ball rolling
=> feat: Paid query flow (partial impl)

.github/workflows/tests.yml
Experiments here: https://github.com/aasseman/indexer-service-rs/pull/1
tl;dr reduced the time by more than an order of magnitude
=> ci: improve rust cache

service/src/server/routes/status.rs
=> fix(#57): malformed indexing status response

Cargo.lock, common/Cargo.toml, common/src/lib.rs, common/src/tap_manager.rs, service/src/main.rs, service/src/query_processor.rs
This is based on #73 and will need to be rebased after #73 has been merged.
Only the last commit in this PR is new.
=> Move TapManager into indexer-common

common/src/address.rs, common/src/indexer_service/http/indexer_service.rs, common/src/lib.rs
adding `/info` endpoint back to query operator info
=> feat(common): add a route /info for operator public key

Cargo.lock, common/Cargo.toml, tap-agent/Cargo.toml, tap-agent/src/tap/rav_storage_adapter.rs, tap-agent/src/tap/sender_account.rs, tap-agent/src/tap/test_utils.rs
=> fix: bump tap-core version to support rav camel case

tap-agent/src/tap/sender_account.rs, tap-agent/src/tap/sender_accounts_manager.rs
=> fix: wait to retry on rav request error

Cargo.lock, common/Cargo.toml, common/src/indexer_service/http/indexer_service.rs
- Add TraceLayer from tower
- Update to use logging on errors so the indexer is able to see when there's a request error.
- Remove unused Errors  due to Clippy
=> feat: add axum tracing and error logging

common/src/escrow_accounts.rs, common/src/test_vectors.rs
authorizedSigners got updated to signers in the tap subgraph
=> Update subgraph calls

common/src/indexer_service/http/config.rs, common/src/indexer_service/http/indexer_service.rs, common/src/tap.rs, common/src/tap/checks.rs, common/src/tap/checks/receipt_max_val_check.rs
=> Add check for receipt value

tap-agent/src/agent/sender_account.rs
=> chore(tap-agent): add comment for panicking the actor

tap-agent/src/agent/sender_allocation.rs
=> fix(tap-agent): execute rav requests until fees equals zero

Cargo.lock, tap-agent/Cargo.toml, tap-agent/maximal-config-example.toml, tap-agent/minimal-config-example.toml, tap-agent/src/agent.rs, tap-agent/src/agent/sender_account.rs, tap-agent/src/agent/sender_accounts_manager.rs, tap-agent/src/agent/sender_allocation.rs, tap-agent/src/config.rs, tap-agent/src/lib.rs, tap-agent/src/tap/context/checks/allocation_id.rs
Making it look more like the config for service: Using only toml files + use shellexpand. 
Note that I also changed the GRT values to u128, because u64 can only go up to ~20GRT or so.
=> feat(tap-agent)!: overhaul config mgmt

tap-agent/Cargo.toml
We need this fix: https://github.com/slawlor/ractor/issues/226
=> fix(tap-agent): update ractor to 0.9.8

common/Cargo.toml, common/src/indexer_service/http/indexer_service.rs
Seen affecting the "misc routes", such as `/version/`
Fixes #205
=> fix(common): 404 on paths with trailing `/`

common/src/tap/checks/deny_list_check.rs
=> fix(common): denylist rejection msg sender address

Cargo.lock
Ran `cargo-update` in an effort to make renovate happier faster.
=> chore(deps): cargo update

tap-agent/src/agent/sender_allocation.rs
We want to reuse the same connection or wait for the older one in case we hit 2 rav requests in a row
=> refactor(tap-agent): reuse same http client

tap-agent/src/agent/sender_allocation.rs
=> refactor: non-blocking backoff

Cargo.toml, config/Cargo.toml, service/Cargo.toml, tap-agent/Cargo.toml
=> fix(all): add missing feature flags

common/src/indexer_service/http/indexer_service.rs, common/src/indexer_service/http/mod.rs, common/src/indexer_service/http/request_handler.rs, service/src/service.rs
Free queries don't require attestation. If signer doesn't exist, it has an early return.
=> fix(common): attestation for free query

.github/workflows/tests.yml, Dockerfile.indexer-service-rs, Dockerfile.indexer-tap-agent, tap-agent/src/agent/sender_allocation.rs
This fixes a bug in https://github.com/launchbadge/sqlx/issues/3461
=> chore: bump to rust 1.80

README.md, service/src/routes/status.rs
This PR Closes #308 
Changes in this PR
- Updated the curl requests and responses in `Readme.md` file
- Added a missing supported field `blockHashFromNumber` for indexingStatus
=> docs: update example endpoints in Readme.md

Cargo.lock, common/Cargo.toml, common/src/indexer_service/http/indexer_service.rs
=> chore: update tower_governor crate

Cargo.lock, tap-agent/Cargo.toml, tap-agent/src/agent/sender_account.rs, tap-agent/src/agent/sender_accounts_manager.rs
=> chore: update ractor crate to 0.13

README.md
=> docs: update indexer-service run command in readme

.github/workflows/containers.yml
https://github.com/orgs/community/discussions/25217#discussioncomment-3246902
=> ci: only push if is not a fork

tap-agent/src/agent/sender_account.rs, tap-agent/src/tracker.rs, tap-agent/src/tracker/generic_tracker.rs, tap-agent/src/tracker/global_tracker.rs, tap-agent/src/tracker/sender_fee_stats.rs, tap-agent/src/tracker/tracker_tests.rs
=> fix: overflow in requesting tracker

common/src/indexer_service/http/indexer_service.rs, common/src/indexer_service/http/request_handler.rs, service/src/service.rs
=> fix: use request from gateway instead of serde req

README.md, docs/Metrics.md, docs/Queries.md, docs/Routes.md, docs/migration-config/README.md
=> docs: new readme and docs

Cargo.lock, crates/service/src/routes/status.rs
Signed-off-by: Joseph Livesey [joseph@semiotic.ai](mailto:joseph@semiotic.ai)
=> supporting querying graph node version

Cargo.lock, crates/service/Cargo.toml, crates/service/src/service.rs, crates/service/src/service/router.rs, crates/service/tests/router_test.rs, crates/service/tests/snapshots/router_test__full_integration_test-2.snap, crates/service/tests/snapshots/router_test__full_integration_test-3.snap
=> refactor: add connection info

Cargo.lock, Cargo.toml, crates/dips/src/server.rs, crates/service/src/middleware/auth.rs, crates/service/src/middleware/auth/tap.rs, crates/service/src/middleware/sender.rs, crates/service/src/middleware/tap_receipt.rs, crates/service/src/service.rs, crates/service/src/service/tap_receipt_header.rs, crates/service/src/tap.rs, crates/service/src/tap/checks/allocation_eligible.rs, crates/service/src/tap/checks/deny_list_check.rs, crates/service/src/tap/checks/receipt_max_val_check.rs, crates/service/src/tap/checks/sender_balance_check.rs, crates/service/src/tap/checks/timestamp_check.rs, crates/service/src/tap/checks/value_check.rs, crates/service/src/tap/receipt.rs, crates/service/src/tap/receipt_store.rs, crates/service/tests/router_test.rs, justfile
- Patch cargo with git and rev for unreleased crate
- Rename TapReceipt to TapHeader
- New service::tap::TapReceipt which represents both v1 and v2
- Update justfile
=> refactor: add horizon support

crates/config/default_values.toml, crates/config/maximal-config-example.toml, crates/config/src/config.rs, crates/service/src/service.rs, crates/service/tests/router_test.rs
=> Make IPFS url configurable

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, Dockerfile.indexer-service-rs, Dockerfile.indexer-tap-agent, crates/dips/src/database.rs, crates/dips/src/lib.rs, crates/dips/src/proto/graphprotocol.gateway.dips.rs, crates/dips/src/proto/graphprotocol.indexer.dips.rs, crates/service/Cargo.toml, crates/service/src/middleware/deployment.rs, crates/service/src/service/router.rs, crates/tap-agent/Cargo.toml, crates/tap-agent/src/agent/sender_account.rs, crates/tap-agent/src/agent/sender_accounts_manager.rs, crates/tap-agent/src/agent/sender_allocation.rs, crates/tap-agent/src/test.rs, docs/Routes.md
...
Signed-off-by: Joseph Livesey <joseph@semiotic.ai>
=> fix: update tap, axum, tonic, alloy dependencies:

crates/service/src/tap/receipt_store.rs
Just a very quick thing I caught as I was reading code.
=> refactor(tap): return optional in process db receipts

Dockerfile.indexer-service-rs, Dockerfile.indexer-tap-agent
=> fix(docker): add libsasl2-2 to images

Cargo.lock, Cargo.toml
Enables Horizon v2 features in the tap-aggregator dependency.
=> fix(build): enable tap-aggregator v2 feature
